version: '3.9'

# services
services:
  # guacd
  guacd:
    container_name: guacamole_backend
    image: guacamole/guacd:latest
    volumes:
    - ./drive:/drive:rw
    - ./record:/record:rw
    networks:
      guacamole_net:
    restart: always

  # postgres
  postgres:
    container_name: guacamole_database
    image: postgres:latest
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
    networks:
      guacamole_net:
    restart: always
    volumes:
    - ./init:/docker-entrypoint-initdb.d:ro
    - ./data:/var/lib/postgresql/data:rw
    
  # guacamole
  guacamole:
    container_name: guacamole_frontend
    image: guacamole/guacamole:latest
    environment:
      - GUACD_HOSTNAME=guacd
      - POSTGRES_DATABASE=guacamole_db
      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_PASSWORD='${POSTGRES_PASSWORD}'
      - POSTGRES_USER='${POSTGRES_USER}'
      - POSTGRESQL_AUTO_CREATE_ACCOUNTS=true
    depends_on:
    - guacd
    - postgres
    links:
    - guacd
    networks:
      - guacamole_net
      - haproxy_net
    restart: always
    volumes:
    - ./drive:/drive:rw

# networks
# create a network 'guacamole_net' in mode 'bridged'
networks:
  guacamole_net:
    driver: bridge
  haproxy_net:
    external: true