version: '3.9'

services:
  guacd:
    image: guacamole/guacd:latest
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_HOSTNAME: "${MYSQL_HOSTNAME}"
    env_file: .env
    ports:
      - 4822:4822
    restart: always
    tty: true
    stdin_open: true

  guacamole:
    image: guacamole/guacamole
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_HOSTNAME: "${MYSQL_HOSTNAME}"
      GUACD_HOSTNAME: "${GUACD_HOSTNAME}"
    env_file: .env
    ports:
      - 8080:8080
    restart: always
    tty: true
    stdin_open: true